project:
  type: website

website:
  title: "Quarto-dark-light"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      light: united
      dark: slate
    css: styles.css
    toc: true



